apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: docker.io/nivitzhaky/hansdson-postgres
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 1
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 8
            periodSeconds: 1